spring:
  application:
    name: gatewayserver
  config:
    import: "configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s


  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "AWF Bank gateway server application"
    version: "1.0"

logging:
  level:
    com:
      awf:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1000







